### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by yanxiatao** [eagle3236/SystemInfo#1]
Traceback (most recent call last):
  File "/root/mcdr/utils/plugin.py", line 68, in run
    super().run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "plugins/SysInfo.py", line 57, in on_info
    send_message(server, info.player, False)
  File "plugins/SysInfo.py", line 32, in send_message
    java_cpu = psutil.Process(proc.pid).cpu_percent(1)
AttributeError: 'NoneType' object has no attribute 'pid'

请问要怎么解决这个问题

**Comment by yanxiatao** [comment]
补充一下，系统环境为centos8

**Comment by eagle3236** [comment]
啊 一直没主意这个issue 现在早就解决了
